"""create tables

Revision ID: 37463c85173b
Revises: 20178cf2ef3e
Create Date: 2026-01-28 17:44:15.485390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37463c85173b'
down_revision: Union[str, Sequence[str], None] = '20178cf2ef3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_agent_table',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ai_agent_name', sa.Text(), nullable=False),
    sa.Column('ai_agent_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ai_agent_id'),
    sa.UniqueConstraint('ai_agent_name')
    )
    op.create_table('llm_prompt_response_table',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('llm_user_prompt_id', sa.BigInteger(), nullable=False),
    sa.Column('llm_prompt_response', sa.Text(), nullable=False),
    sa.Column('ai_agent_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_prompt_table',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('llm_system_prompt', sa.Text(), nullable=False),
    sa.Column('ai_agent_id', sa.Text(), nullable=False),
    sa.Column('ai_model', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ai_agent_id')
    )
    op.create_table('user_prompt_table',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('llm_user_prompt', sa.Text(), nullable=False),
    sa.Column('ai_agent_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_prompt_table')
    op.drop_table('system_prompt_table')
    op.drop_table('llm_prompt_response_table')
    op.drop_table('ai_agent_table')
    # ### end Alembic commands ###
