"""create llm_prompt_response_table

Revision ID: 5cffdaf15574
Revises: b20ac25ffcd0
Create Date: 2026-01-28 14:37:38.691867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cffdaf15574'
down_revision: Union[str, Sequence[str], None] = 'b20ac25ffcd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_prompt_response_table',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('llm_user_prompt_id', sa.BigInteger(), nullable=False),
    sa.Column('llm_prompt_response', sa.Text(), nullable=False),
    sa.Column('ai_agent_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('llm_user_prompt_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_prompt_response_table')
    # ### end Alembic commands ###
