"""update verified_payload_table

Revision ID: c83a69a00dc3
Revises: dc6c76b807a8
Create Date: 2026-02-09 12:19:22.949700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c83a69a00dc3'
down_revision: Union[str, Sequence[str], None] = 'dc6c76b807a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('verified_payload_table_verified_payload_key'), 'verified_payload_table', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('verified_payload_table_verified_payload_key'), 'verified_payload_table', ['verified_payload'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
