"""create verified_payload_table

Revision ID: dc6c76b807a8
Revises: ee61a80e58f8
Create Date: 2026-02-09 11:54:50.511449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc6c76b807a8'
down_revision: Union[str, Sequence[str], None] = 'ee61a80e58f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verified_payload_table',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('verified_payload', sa.Text(), nullable=False),
    sa.Column('ai_agent_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ai_agent_id'),
    sa.UniqueConstraint('verified_payload')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verified_payload_table')
    # ### end Alembic commands ###
