"""create attached_ai_tools_table

Revision ID: ee61a80e58f8
Revises: 37463c85173b
Create Date: 2026-02-03 13:43:00.007389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee61a80e58f8'
down_revision: Union[str, Sequence[str], None] = '37463c85173b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attached_ai_tools_table',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ai_agent_id', sa.Text(), nullable=False),
    sa.Column('agent_tool_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ai_agent_id', 'agent_tool_name', name='uq_ai_agent_tool')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attached_ai_tools_table')
    # ### end Alembic commands ###
