"""create user_prompt_table

Revision ID: ff1251aeb20c
Revises: 027e8d073bf8
Create Date: 2026-01-27 14:12:44.265534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff1251aeb20c'
down_revision: Union[str, Sequence[str], None] = '027e8d073bf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_prompt_table',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('llm_user_prompt', sa.Text(), nullable=False),
    sa.Column('ai_agent_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_prompt_table')
    # ### end Alembic commands ###
